defmodule SecondBrain.Lineage do
  @moduledoc """
  Flow-doc provenance: the `analysis → plan → thread → PR → flow` chain that
  produced each `meta/flows/*.md` doc.

  The **canonical source** is the flow doc's `attribution.from` back-links
  (see the resource-attribution policy) — there is no hand-kept lineage data.
  Each ref is classified by its governance path (`/meta/analysis/` →
  analysis, `/meta/plans/` → plan, `/meta/threads/` → thread), and the PR hop
  is resolved through each thread doc's `pr:` anchor — the same anchors the
  session-capture policy already maintains. A flow built across several
  sessions simply carries several thread refs (appended by
  `/create-pull-request`'s stamping step, `from` being append-only).

  From those edges this module derives two never-hand-kept views, on the same
  generated-artifact discipline as `CLAUDE.md` and `meta/registry.md`:

    * a per-doc **blockquote** materialized between `lineage:start`/`lineage:end`
      markers at the top of each flow doc (`materialize/1`), and
    * a cross-flow **flowchart index** at `meta/flows/lineage.md` (Mermaid graph +
      a dependency-free table), written by `write_index/1`.

  `check/1` re-derives both and reports staleness for the `--check` CI gate.

  (`parse_lineage_block/1` remains only as the migration reader the
  attribution backfill used to convert the retired hand-kept `lineage:`
  blocks into `attribution.from` refs.)
  """

  alias SecondBrain.Frontmatter

  @flows_dir "meta/flows"
  @index_output "meta/flows/lineage.md"
  @generated_files ~w(index.md lineage.md)

  @begin_marker "<!-- lineage:start (generated by `mix brain.lineage --materialize`; edit the `lineage:` frontmatter, not this block) -->"
  @end_marker "<!-- lineage:end -->"

  defmodule Flow do
    @moduledoc false
    @enforce_keys [:path, :slug]
    defstruct [:path, :slug, :title, analysis: [], plan: [], thread: [], pr: [], labels: %{}]

    @doc "True when the flow carries at least one lineage hop."
    def has_lineage?(%__MODULE__{analysis: a, plan: p, thread: t, pr: r}),
      do: a != [] or p != [] or t != [] or r != []
  end

  @doc "Path of the generated flowchart index, relative to repo root."
  def index_output_path, do: @index_output

  @doc "Relative paths of every flow doc (excluding the generated index/lineage files)."
  def flow_paths(root \\ File.cwd!()) do
    root
    |> Path.join(@flows_dir <> "/*.md")
    |> Path.wildcard()
    |> Enum.map(&Path.relative_to(&1, root))
    |> Enum.reject(&(Path.basename(&1) in @generated_files))
    |> Enum.sort()
  end

  @doc "Scan every flow doc and return a list of `%Flow{}`, sorted by path."
  @spec scan(String.t()) :: [Flow.t()]
  def scan(root \\ File.cwd!()) do
    root
    |> flow_paths()
    |> Enum.map(&load_flow(&1, root))
  end

  defp load_flow(rel_path, root) do
    content = root |> Path.join(rel_path) |> File.read!()
    fm = content |> Frontmatter.parse!() |> Map.fetch!(:frontmatter)
    from = attribution_from(fm)

    analysis = Enum.filter(from, &String.starts_with?(&1, "/meta/analysis/"))
    plan = Enum.filter(from, &String.starts_with?(&1, "/meta/plans/"))
    thread = Enum.filter(from, &String.starts_with?(&1, "/meta/threads/"))
    pr = thread |> Enum.flat_map(&thread_prs(root, &1)) |> Enum.uniq()

    labels =
      [rel_path | analysis ++ plan ++ thread]
      |> Enum.filter(&is_binary/1)
      |> Map.new(&{&1, title_of(root, &1)})

    %Flow{
      path: rel_path,
      slug: rel_path |> Path.basename() |> String.trim_trailing(".md"),
      title: fm["title"],
      analysis: analysis,
      plan: plan,
      thread: thread,
      pr: pr,
      labels: labels
    }
  end

  defp attribution_from(fm) do
    case fm["attribution"] do
      %{"from" => from} -> from |> List.wrap() |> Enum.filter(&is_binary/1)
      _ -> []
    end
  end

  # The PR hop: each thread doc records the PR that landed it (`pr:` — the
  # thread's durable anchor per the session-capture policy).
  defp thread_prs(root, "/" <> rel) do
    with {:ok, content} <- File.read(Path.join(root, rel)),
         {:ok, %{frontmatter: %{"pr" => pr}}} <- Frontmatter.parse(content) do
      pr |> List.wrap() |> Enum.filter(&is_integer/1)
    else
      _ -> []
    end
  end

  defp thread_prs(_root, _ref), do: []

  # Human label for a referenced doc: its frontmatter title, else the basename.
  defp title_of(root, path) do
    rel = String.trim_leading(path, "/")
    fallback = rel |> Path.basename() |> String.trim_trailing(".md")

    with {:ok, content} <- File.read(Path.join(root, rel)),
         {:ok, %{frontmatter: %{"title" => title}}} when is_binary(title) <-
           Frontmatter.parse(content) do
      title
    else
      _ -> fallback
    end
  end

  # --- lineage block parsing (nested; the flat Frontmatter parser can't) -----

  @doc false
  def parse_lineage_block(content) do
    content
    |> frontmatter_lines()
    |> lineage_lines()
    |> parse_lineage_lines()
  end

  defp frontmatter_lines(content) do
    normalized = String.replace(content, "\r\n", "\n")

    case normalized do
      "---\n" <> rest ->
        [yaml | _] = String.split(rest, "\n---", parts: 2)
        String.split(yaml, "\n")

      _ ->
        []
    end
  end

  # Take the `lineage:` line's children — subsequent lines indented deeper than
  # the `lineage:` key itself — stopping at the next same-or-shallower key.
  defp lineage_lines(lines) do
    case Enum.split_while(lines, &(not lineage_key?(&1))) do
      {_before, [lineage_head | rest]} ->
        base_indent = indent_of(lineage_head)

        Enum.take_while(rest, fn line ->
          String.trim(line) == "" or indent_of(line) > base_indent
        end)

      {_before, []} ->
        []
    end
  end

  defp lineage_key?(line), do: Regex.match?(~r/^\s*lineage:\s*$/, line)
  defp indent_of(line), do: String.length(line) - String.length(String.trim_leading(line))

  defp parse_lineage_lines(lines) do
    {map, _current} =
      Enum.reduce(lines, {%{}, nil}, fn line, {acc, current} ->
        trimmed = String.trim(line)

        cond do
          trimmed == "" ->
            {acc, current}

          match = Regex.run(~r/^-\s+(.*)$/, trimmed) ->
            [_, item] = match
            key = current || :thread
            {Map.update(acc, key, [scalar(item)], &(&1 ++ [scalar(item)])), current}

          match = Regex.run(~r/^([a-z_]+):\s*(.*)$/, trimmed) ->
            [_, raw_key, raw_val] = match
            key = safe_key(raw_key)

            if raw_val == "" do
              {Map.put_new(acc, key, []), key}
            else
              {Map.put(acc, key, parse_value(raw_val)), key}
            end

          true ->
            {acc, current}
        end
      end)

    map
  end

  @known_keys ~w(analysis plan thread pr)
  defp safe_key(k) when k in @known_keys, do: String.to_atom(k)
  defp safe_key(_), do: :unknown

  # A field value is normalized to a list: scalar → [v], inline [a, b] → [a, b].
  defp parse_value("[" <> _ = inline) do
    inline
    |> String.trim_leading("[")
    |> String.trim_trailing("]")
    |> String.split(",")
    |> Enum.map(&scalar(String.trim(&1)))
    |> Enum.reject(&(&1 == ""))
  end

  defp parse_value(v), do: [scalar(v)]

  defp scalar(v) do
    v = v |> String.trim() |> String.trim_leading("\"") |> String.trim_trailing("\"")

    case Integer.parse(v) do
      {int, ""} -> int
      _ -> v
    end
  end

  # --- per-doc blockquote ----------------------------------------------------

  @doc """
  Render the generated lineage blockquote for a flow, or `nil` when the flow has
  no lineage recorded.
  """
  def blockquote(%Flow{} = flow) do
    if Flow.has_lineage?(flow) do
      link = &doc_link(&1, flow.labels)

      chain =
        [
          stage_phrase("identified in", flow.analysis, link),
          stage_phrase("designed in", flow.plan, link),
          stage_phrase("built in", flow.thread, link),
          stage_phrase("merged in", flow.pr, &pr_link/1)
        ]
        |> Enum.reject(&is_nil/1)
        |> Enum.join(" → ")
        |> capitalize_first()

      "> **Lineage** *(generated — `mix brain.lineage`; read [the full chart](/#{@index_output})).* " <>
        chain <> "."
    end
  end

  defp capitalize_first(""), do: ""

  defp capitalize_first(str),
    do: String.upcase(String.first(str)) <> String.slice(str, 1..-1//1)

  defp stage_phrase(_verb, [], _fmt), do: nil

  defp stage_phrase(verb, values, fmt),
    do: verb <> " " <> Enum.map_join(values, ", ", fmt)

  defp doc_link(path, labels) when is_binary(path) do
    abs = if String.starts_with?(path, "/"), do: path, else: "/" <> path
    label = Map.get(labels, path) || path |> Path.basename() |> String.trim_trailing(".md")
    "[#{label}](#{abs})"
  end

  defp pr_link(n), do: "PR ##{n}"

  @doc """
  Return `content` with its lineage blockquote materialized: replace the region
  between the markers if present, else insert a fresh marker block right after
  the doc's first `# ` H1. A flow with no lineage is returned unchanged.
  """
  def materialize(%Flow{} = flow, content) do
    case blockquote(flow) do
      nil -> content
      quote_md -> put_block(content, @begin_marker <> "\n" <> quote_md <> "\n" <> @end_marker)
    end
  end

  defp put_block(content, block) do
    marker_re = ~r/#{Regex.escape(@begin_marker)}.*?#{Regex.escape(@end_marker)}/s

    if Regex.match?(marker_re, content) do
      # Function replacement avoids `\N` backreference interpretation in `block`.
      Regex.replace(marker_re, content, fn _ -> block end)
    else
      insert_after_h1(content, block)
    end
  end

  defp insert_after_h1(content, block) do
    lines = String.split(content, "\n")
    idx = Enum.find_index(lines, &String.starts_with?(&1, "# "))

    case idx do
      nil ->
        block <> "\n\n" <> content

      i ->
        {before, rest} = Enum.split(lines, i + 1)
        Enum.join(before ++ ["", block] ++ rest, "\n")
    end
  end

  # --- flowchart index -------------------------------------------------------

  @doc "Render the full generated `meta/flows/lineage.md` document."
  def render_index(root \\ File.cwd!()) do
    flows = scan(root)
    with_lineage = Enum.filter(flows, &Flow.has_lineage?/1)
    without = Enum.reject(flows, &Flow.has_lineage?/1)

    """
    <!--
      GENERATED FILE — do not edit by hand.
      Source of truth: the `attribution.from` refs of each meta/flows/*.md doc + thread `pr:` anchors.
      Regenerate:      mix brain.lineage
      Verify (CI):     mix brain.lineage --check
    -->

    # Flow lineage — how each flow came to be

    Every flow doc records the arc that produced it — the originating `analysis`
    (a problem identified against evidence), the `plan` that designed it, the
    `thread` (the captured session that built it), and the merging PR. This page is
    the cross-flow view, derived from every doc's `attribution.from` back-links
    (classified by governance path) plus each thread's `pr:` anchor — see the
    [resource-attribution policy](/meta/policy/resource-attribution.md). See
    the [flows index](/meta/flows/index.md) for the flows themselves and the
    [flow-lineage plan](/meta/plans/flow-lineage-index.md) for the design.

    ## Flowchart

    ```mermaid
    #{mermaid(with_lineage)}
    ```

    ## Table

    | Flow | Analysis | Plan | Thread | PR |
    |------|----------|------|--------|----|
    #{Enum.map_join(with_lineage, "\n", &table_row/1)}
    #{without_section(without)}
    """
  end

  defp mermaid(flows) do
    header = "flowchart LR"

    body =
      flows
      |> Enum.with_index()
      |> Enum.map_join("\n", fn {flow, i} -> mermaid_chain(flow, i) end)

    header <> "\n" <> body
  end

  defp mermaid_chain(%Flow{} = flow, i) do
    nodes =
      [
        {:analysis, flow.analysis},
        {:plan, flow.plan},
        {:thread, flow.thread},
        {:pr, flow.pr}
      ]
      |> Enum.filter(fn {_stage, vals} -> vals != [] end)
      |> Enum.map(fn {stage, vals} -> {node_id(i, stage), node_label(stage, vals)} end)

    flow_node = {node_id(i, :flow), "flow: " <> flow.slug}
    all = nodes ++ [flow_node]

    decls = Enum.map_join(all, "\n", fn {id, label} -> "  #{id}[\"#{escape(label)}\"]" end)
    edges = all |> Enum.map(&elem(&1, 0)) |> Enum.chunk_every(2, 1, :discard)
    edge_lines = Enum.map_join(edges, "\n", fn [a, b] -> "  #{a} --> #{b}" end)

    decls <> "\n" <> edge_lines
  end

  defp node_id(i, :analysis), do: "f#{i}a"
  defp node_id(i, :plan), do: "f#{i}p"
  defp node_id(i, :thread), do: "f#{i}t"
  defp node_id(i, :pr), do: "f#{i}r"
  defp node_id(i, :flow), do: "f#{i}f"

  defp node_label(:pr, prs), do: "PR " <> Enum.map_join(prs, ", ", &"##{&1}")
  defp node_label(stage, vals), do: "#{stage}: " <> Enum.map_join(vals, ", ", &basename/1)

  defp basename(path) when is_binary(path),
    do: path |> Path.basename() |> String.trim_trailing(".md")

  defp basename(other), do: to_string(other)

  defp escape(label), do: String.replace(label, "\"", "'")

  defp table_row(%Flow{} = flow) do
    link = &doc_link(&1, flow.labels)

    "| #{link.(flow.path)} | #{cell(flow.analysis, link)} | " <>
      "#{cell(flow.plan, link)} | #{cell(flow.thread, link)} | " <>
      "#{cell(flow.pr, &pr_link/1)} |"
  end

  defp cell([], _fmt), do: "—"
  defp cell(values, fmt), do: Enum.map_join(values, "<br>", fmt)

  defp without_section([]), do: ""

  defp without_section(flows) do
    rows = Enum.map_join(flows, "\n", fn f -> "- #{doc_link(f.path, f.labels)}" end)

    "\n## No lineage recorded yet\n\nThese flow docs carry no `lineage:` block " <>
      "(they may predate the convention or have no distinct origin):\n\n" <> rows <> "\n"
  end

  # --- write / check ---------------------------------------------------------

  @doc """
  Materialize every flow doc's blockquote and (re)write the flowchart index.
  Returns the list of paths written.
  """
  def write(root \\ File.cwd!()) do
    written =
      root
      |> scan()
      |> Enum.flat_map(fn flow ->
        path = Path.join(root, flow.path)
        content = File.read!(path)
        new = materialize(flow, content)

        if new == content do
          []
        else
          File.write!(path, new)
          [flow.path]
        end
      end)

    index_path = Path.join(root, @index_output)
    rendered = render_index(root)

    if File.exists?(index_path) and File.read!(index_path) == rendered do
      written
    else
      File.write!(index_path, rendered)
      written ++ [@index_output]
    end
  end

  @doc """
  Check the on-disk views match a fresh derivation. Returns `:ok` or
  `{:stale, [paths]}`.
  """
  def check(root \\ File.cwd!()) do
    stale_docs =
      root
      |> scan()
      |> Enum.filter(fn flow ->
        content = root |> Path.join(flow.path) |> File.read!()
        materialize(flow, content) != content
      end)
      |> Enum.map(& &1.path)

    index_path = Path.join(root, @index_output)
    on_disk = if File.exists?(index_path), do: File.read!(index_path), else: ""
    stale_index = if render_index(root) == on_disk, do: [], else: [@index_output]

    case stale_docs ++ stale_index do
      [] -> :ok
      stale -> {:stale, stale}
    end
  end
end
